##
## EPITECH PROJECT, 2019
## CPE_dante_2019
## File description:
## Makefile
##

all:
	make -C ./generator
	make -C ./solver

clean:
	make -C ./generator clean
	make -C ./solver clean

fclean:
	make -C ./generator fclean
	make -C ./solver fclean

re:	fclean all